apiVersion: v1
kind: BuildConfig
metadata:
  name: jenkins-build
spec:
  source:                       
    git:
      uri: https://github.com/redhat-multiarch-qe/multiarch-ci-provisioner
    type: Git
  strategy:                     
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jenkins-2-centos7:latest
        namespace: openshift
    type: Source
  output:                       
    to:
      kind: ImageStreamTag
      name: jenkins:latest


